### ISSUE TITLE
Error running `postal upgrade`

### ISSUE THREAD

**Issue by acsfer** [postalserver/postal#1577]
## Describe the bug

Running postal upgrade returns error, and application stops working

## To Reproduce

```
# postal upgrade
warning: redirecting to https://github.com/postalserver/install/
From https://postalserver.io/start/install
 * branch            main       -> FETCH_HEAD
Already up to date.
No version specified, using latest available version...
Upgrading to 2.0.0
Pulling web      ... done
Pulling smtp     ... done
Pulling worker   ... done
Pulling cron     ... done
Pulling requeuer ... done
Creating postal_runner_run ... done
Migrating database
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateAuthieSessions < ActiveRecord::Migration[4.2]
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:528:in `inherited'
/opt/postal/app/db/migrate/20161003195209_create_authie_sessions.authie.rb:2:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:986:in `load_migration'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:982:in `migration'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/opt/postal/app/bin/bundle:3:in `load'
/opt/postal/app/bin/bundle:3:in `<main>'

Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateAuthieSessions < ActiveRecord::Migration[4.2]
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:528:in `inherited'
/opt/postal/app/db/migrate/20161003195209_create_authie_sessions.authie.rb:2:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:986:in `load_migration'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:982:in `migration'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:977:in `disable_ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1350:in `use_transaction?'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1342:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1262:in `each'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1210:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1036:in `up'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/migration.rb:1011:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/local/bundle/gems/activerecord-5.2.6/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/opt/postal/app/bin/bundle:3:in `load'
/opt/postal/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
ERROR: 1
```

## Expected behaviour

Upgrade should run smoothly

## Environment details 

 - Ubutnu 20.04
 - Version 22

**Comment by adamcooke** [comment]
This sounds like you're running the migrations on either an empty database or a database with a very old version of the schema in it.

**Comment by acsfer** [comment]
Well, i just installed Post v2 on a newly created VPS, connect to GUI and tested it.
I've run the command to "see what happens". 🤔 

Let me restore the snapshot and start again, i'll provide feedback.

**Comment by acsfer** [comment]
My bad; installed it a little quickly, and didn't see that MariaDB data wasn't stored outside the container (upgrading it deleted the data...).

Fixed by passing `-v /opt/postal/mariadb-data:/var/lib/mysql` on the docker un command.
