### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by uhlhosting** [postalserver/postal#1734]
## To Reproduce

1. Go to '/login/reset'
2. Click on 'Reset Password'
3. Get redirected to a 404 page.

## Screenshots

<img width="612" alt="image" src="https://user-images.githubusercontent.com/6324047/143283282-bfbadc55-5369-4e5f-9eba-0a0c9a09feff.png">

## Environment details 

 - OS: macOS
 - Browser safari
 - Version latest
 - Type desktop

## Additional information/context

Add any other context about the problem here. It is particularily useful to include log extracts (after removing private information).

**Comment by willpower232** [comment]
Can you check the log files? There should be an exception and stack trace which will be the only way to know what has gone wrong.

**Comment by uhlhosting** [comment]
@willpower232 so I should grab the logs from Web container? Or any specific logs?

**Comment by willpower232** [comment]
it would be the web container as that is what reported the error to you.

**Comment by uhlhosting** [comment]
So this is all we got:

@willpower232  here are the logs:

```
86.49.246.172 - - [26/Nov/2021:20:16:27 +0000] "GET /login/reset HTTP/1.1" 200 - 0.0789
86.49.246.172 - - [26/Nov/2021:20:16:36 +0000] "POST /500 HTTP/1.1" 500 1477 1.0404
86.49.246.172 - - [26/Nov/2021:20:17:03 +0000] "GET /login/reset HTTP/1.1" 200 - 0.0035
86.49.246.172 - - [26/Nov/2021:20:17:04 +0000] "GET / HTTP/1.1" 302 - 0.0023
86.49.246.172 - - [26/Nov/2021:20:17:04 +0000] "GET /login?return_to=%2F HTTP/1.1" 200 - 0.0035
86.49.246.172 - - [26/Nov/2021:20:17:08 +0000] "GET /404 HTTP/1.1" 404 1564 0.0016
86.49.246.172 - - [26/Nov/2021:20:17:14 +0000] "POST /500 HTTP/1.1" 500 1477 0.1140
root@post:/opt/postal# 
```

**Comment by uhlhosting** [comment]
Maybe it needs more debug enabled?

**Comment by willpower232** [comment]
Ah that is the log for puma which is what the docker command is. I think you can go into the container and look for the rails log files with `postal bash web`

**Comment by uhlhosting** [comment]
@willpower232 here are the production.log

```
I, [2022-02-09T15:41:19.655071 #9]  INFO -- : [83dd391e-3f5f-41b1-8652-2089daad0a72] Completed 200 OK in 50ms (Views: 14.9ms | ActiveRecord: 29.7ms)
I, [2022-02-09T15:50:09.809402 #9]  INFO -- : [43a89ce9-337c-4722-a93a-2b42d79fa4f1] Started DELETE "/logout" for 172.225.38.90 at 2022-02-09 15:50:09 +0000
I, [2022-02-09T15:50:09.810058 #9]  INFO -- : [43a89ce9-337c-4722-a93a-2b42d79fa4f1] Processing by SessionsController#destroy as HTML
I, [2022-02-09T15:50:09.810105 #9]  INFO -- : [43a89ce9-337c-4722-a93a-2b42d79fa4f1]   Parameters: {"authenticity_token"=>"a+UdLV5AL9ZWK+EOEk2KrbKlx6jeaGs/JJNde1+AVKXDpLR74CgKAagecydYcZdx5g9tSDsVFkSQdqnNGRo4JA=="}
I, [2022-02-09T15:50:09.927072 #9]  INFO -- : [43a89ce9-337c-4722-a93a-2b42d79fa4f1] Redirected to https://post.uhlhosting.ch/login
I, [2022-02-09T15:50:09.927370 #9]  INFO -- : [43a89ce9-337c-4722-a93a-2b42d79fa4f1] Completed 302 Found in 117ms (ActiveRecord: 111.1ms)
I, [2022-02-09T15:50:10.013240 #9]  INFO -- : [d711d6cc-2cae-4b2f-bf66-82f20ae4a5b6] Started GET "/login" for 172.225.38.90 at 2022-02-09 15:50:10 +0000
I, [2022-02-09T15:50:10.017497 #9]  INFO -- : [d711d6cc-2cae-4b2f-bf66-82f20ae4a5b6] Processing by SessionsController#new as HTML
I, [2022-02-09T15:50:10.019380 #9]  INFO -- : [d711d6cc-2cae-4b2f-bf66-82f20ae4a5b6]   Rendering sessions/new.html.haml within layouts/sub
I, [2022-02-09T15:50:10.023244 #9]  INFO -- : [d711d6cc-2cae-4b2f-bf66-82f20ae4a5b6]   Rendered sessions/new.html.haml within layouts/sub (3.8ms)
I, [2022-02-09T15:50:10.026794 #9]  INFO -- : [d711d6cc-2cae-4b2f-bf66-82f20ae4a5b6] Completed 200 OK in 9ms (Views: 8.3ms | ActiveRecord: 0.0ms)
I, [2022-02-09T15:50:14.503251 #9]  INFO -- : [d925ea32-2fa9-4d09-946a-c733ea197fa4] Started GET "/login/reset" for 172.225.38.90 at 2022-02-09 15:50:14 +0000
I, [2022-02-09T15:50:14.503766 #9]  INFO -- : [d925ea32-2fa9-4d09-946a-c733ea197fa4] Processing by SessionsController#begin_password_reset as HTML
I, [2022-02-09T15:50:14.513944 #9]  INFO -- : [d925ea32-2fa9-4d09-946a-c733ea197fa4]   Rendering sessions/begin_password_reset.html.haml within layouts/sub
I, [2022-02-09T15:50:14.516378 #9]  INFO -- : [d925ea32-2fa9-4d09-946a-c733ea197fa4]   Rendered sessions/begin_password_reset.html.haml within layouts/sub (2.3ms)
I, [2022-02-09T15:50:14.516879 #9]  INFO -- : [d925ea32-2fa9-4d09-946a-c733ea197fa4] Completed 200 OK in 13ms (Views: 3.1ms | ActiveRecord: 0.0ms)
I, [2022-02-09T15:50:17.836451 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82] Started POST "/login/reset" for 172.225.38.90 at 2022-02-09 15:50:17 +0000
I, [2022-02-09T15:50:17.837026 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82] Processing by SessionsController#begin_password_reset as HTML
I, [2022-02-09T15:50:17.837102 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"WNXuYqFNF305AcQxINFvxyouYdw3hHw5isyeFEDuy1hrq7I878Lp25NIoLF5LY33T0MAx/shM79v42vaAXXKhg==", "return_to"=>"", "email_address"=>"cosmin@uhlhost.net", "commit"=>"Continue"}
I, [2022-02-09T15:50:17.872800 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82]   Rendering app_mailer/password_reset.text.erb
I, [2022-02-09T15:50:17.873329 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82]   Rendered app_mailer/password_reset.text.erb (0.4ms)
I, [2022-02-09T15:50:17.978518 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82] Sent mail to cosmin@uhlhost.net (104.8ms)
I, [2022-02-09T15:50:17.978752 #9]  INFO -- : [d34d6204-592c-4684-854f-e9650e0bef82] Completed 500 Internal Server Error in 142ms (ActiveRecord: 15.9ms)
F, [2022-02-09T15:50:17.979334 #9] FATAL -- : [d34d6204-592c-4684-854f-e9650e0bef82]   
F, [2022-02-09T15:50:17.979390 #9] FATAL -- : [d34d6204-592c-4684-854f-e9650e0bef82] Errno::ECONNRESET (Connection reset by peer - SSL_connect):
F, [2022-02-09T15:50:17.979436 #9] FATAL -- : [d34d6204-592c-4684-854f-e9650e0bef82]   
F, [2022-02-09T15:50:17.979486 #9] FATAL -- : [d34d6204-592c-4684-854f-e9650e0bef82] app/models/user/authentication.rb:33:in `begin_password_reset'
[d34d6204-592c-4684-854f-e9650e0bef82] app/controllers/sessions_controller.rb:42:in `begin_password_reset'
[d34d6204-592c-4684-854f-e9650e0bef82] lib/postal/tracking_middleware.rb:12:in `call'
postal@post:~/app/log$ 
```

**Comment by uhlhosting** [comment]
I got this in my postal.yml

`smtp:
  host: 127.0.0.1
  port: 25
  username: uhl-hosting/uhl-sites
  password: IlsylcZyuxArnuduTOgnTavY
  from_name: "Postal"
  from_address: "postal@uhlhosting.ch"`

**Comment by uhlhosting** [comment]
<img width="318" alt="image" src="https://user-images.githubusercontent.com/6324047/153263930-37a7e1f5-7b2b-4458-b845-b271f237f814.png">
Managed to solve the issue, by disabling the TLS/SSL since its not working with the SSL generated by Caddy.

**Comment by willpower232** [comment]
definitely change that api key now its been in the issue though

**Comment by uhlhosting** [comment]
> definitely change that api key now its been in the issue though

what API key you mean specifically?

**Comment by willpower232** [comment]
when you shared part of your config file above, "I got this in my postal.yml", that information shouldn't be public

**Comment by uhlhosting** [comment]
will update it.
