### ISSUE TITLE
Mysql2::Error: Incorrect string value: '\xF1\xF7\xE5\xF2 \xF3...' for column `postal-server-1`.`messages`.`subject` at row 1

### ISSUE THREAD

**Issue by lzadjsf** [postalserver/postal#2049]
Describe the bug

Some e-mail hasn't been accepted for delivery with error in smtp server DEBUG 

Send an email with cp1251 encoded text inside Subject and mail body and got error in debug output.

## Expected behaviour

E-mail accepted for delivery and delivered to recipient

Environment details

    OS: Debian 11
    Version: 2.1.1

## Additional information/context

postal-smtp-1 container DEBUG output
Some data has been obfuscated for security reasons.

[9] [2022-06-30T13:09:16.052] DEBUG -- : [GLWKJO]    Connection opened from ::ffff:<ipv4>
[9] [2022-06-30T13:09:16.052] DEBUG -- : [GLWKJO]    Client identified as ::ffff:<ipv4>
[9] [2022-06-30T13:09:16.053] DEBUG -- : [GLWKJO] <= EHLO localhost
[9] [2022-06-30T13:09:16.054] DEBUG -- : [GLWKJO] => 250-My capabilities are
[9] [2022-06-30T13:09:16.055] DEBUG -- : [GLWKJO] => 250-STARTTLS
[9] [2022-06-30T13:09:16.055] DEBUG -- : [GLWKJO] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[9] [2022-06-30T13:09:16.055] DEBUG -- : [GLWKJO] <= AUTH CRAM-MD5
[9] [2022-06-30T13:09:16.055] DEBUG -- : [GLWKJO] => 334 PDM4OGEzNzFhN2NkN2NhYjJmNDQ4QG1sLm1vYmlmaXRuZXNzLnJ1Pg==
[9] [2022-06-30T13:09:16.055] DEBUG -- : [GLWKJO] <= bW9iaWZpdG5lc3MvbW9iaWZpdG5lc3MtcnUgNjA3ZGNiOWNkN2Q5NWU2MzMxYjFlNTgxNDRiYjZkNDE=
[9] [2022-06-30T13:09:16.059] DEBUG -- : [GLWKJO] => 235 Granted for <Username>
[9] [2022-06-30T13:09:16.059] DEBUG -- : [GLWKJO] <= MAIL FROM:<noreply@example.com>
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] => 250 OK
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] <= RCPT TO:<example@example.com>
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] Added external address 'example@example.com'
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] => 250 OK
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] <= DATA
[9] [2022-06-30T13:09:16.060] DEBUG -- : [GLWKJO] => 354 Go ahead
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= To: example@example.com
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= Subject: ORG NAME: ���� ������
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= X-PHP-Originating-Script: 33:function.inc.php
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= From: "Example" <noreply@example.com>
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= Reply-To: "Example" <noreply@example.com>
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= MIME-Version: 1.0
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= Content-type: text/plain;charset=windows-1251
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= 
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= ������ ���� 4205 �� ������� Fly  �� ����� 375 ���.
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= ������� �����: 29 ����
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= 
[9] [2022-06-30T13:09:16.061] DEBUG -- : [GLWKJO] <= .
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] An error occurred while processing data from a client.
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] Mysql2::Error: Incorrect string value: '\xF1\xF7\xE5\xF2 \xF3...' for column `postal-server-1`.`messages`.`subject` at row 1
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/database.rb:224:in `block in insert'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/database.rb:223:in `insert'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/message.rb:567:in `_create'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/message_db/message.rb:206:in `save'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/client.rb:452:in `block in finished'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/client.rb:438:in `each'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/client.rb:438:in `finished'
[9] [2022-06-30T13:09:16.067] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/client.rb:375:in `block in data'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/client.rb:49:in `handle'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:161:in `block (2 levels) in run_event_loop'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/postal/smtp_server/server.rb:261:in `run'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /opt/postal/app/bin/rake:4:in `<top (required)>'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
[9] [2022-06-30T13:09:16.068] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /opt/postal/app/bin/bundle:3:in `load'
[9] [2022-06-30T13:09:16.069] ERROR -- : [GLWKJO] /opt/postal/app/bin/bundle:3:in `<main>'

**Comment by flakerimi** [comment]
Encoding should be `utf8mb4` in order to support special characters.
