### ISSUE TITLE
MySQL 8.0?

### ISSUE THREAD

**Issue by phtmgt** [postalserver/postal#2183]
## Describe the bug

Every 10 requests result in error 500.

## To Reproduce

1. Upgrade to MySQL 8
2. Upgrade to latest version of postal (as of 2022.10.13)
3. Start using the web interface

## Expected behaviour

No error

## Environment details 

 - OS: Ubuntu 22 + docker
 - Version 2.1.2

## Additional information/context

```
[8] [2022-10-14T04:35:19.793] INFO -- : Completed 500 Internal Server Error in 42ms (ActiveRecord: 26.8ms)
[8] [2022-10-14T04:35:19.795] FATAL -- :
[8] [2022-10-14T04:35:19.795] FATAL -- : ActionView::Template::Error (The client was disconnected by the server because of in$
[8] [2022-10-14T04:35:19.795] FATAL -- :     26:             = link_to [organization, server], :class => 'largeList__link' do
    27:               %span.largeList__rightLabel.label{:class => "label--serverStatus-#{server.status.underscore}"}= t("serv$
    28:               %p= server.name
    29:               %p.largeList__subText #{number_with_precision server.message_rate, :precision => 2} messages/minute
    30:       .js-searchable__empty.is-hidden
    31:         .noData.noData--clean
    32:           %p.noData__title No servers were found...
[8] [2022-10-14T04:35:19.795] FATAL -- :
[8] [2022-10-14T04:35:19.795] FATAL -- : lib/postal/message_db/database.rb:319:in `query_on_connection'
lib/postal/message_db/database.rb:311:in `block in query'
lib/postal/message_db/mysql.rb:20:in `client'
lib/postal/message_db/database.rb:342:in `with_mysql'
lib/postal/message_db/database.rb:310:in `query'
lib/postal/message_db/live_stats.rb:34:in `total'
app/models/server.rb:135:in `message_rate'
app/views/servers/index.html.haml:29:in `block (2 levels) in _app_views_servers_index_html_haml___1505894316457539718_4717191$
app/views/servers/index.html.haml:26:in `block in _app_views_servers_index_html_haml___1505894316457539718_47171917758060'
app/views/servers/index.html.haml:24:in `each'
app/views/servers/index.html.haml:24:in `_app_views_servers_index_html_haml___1505894316457539718_47171917758060'
lib/postal/tracking_middleware.rb:12:in `call'
```

**Comment by plamenh** [comment]
For anyone having similar issues - I solved it by replacing mysql with MariaDB. Immediately fixed the issue.

**Comment by willpower232** [comment]
Are you able to see the rest of the error message? It gets cut off `The client was disconnected by the server because of in...`

**Comment by plamenh** [comment]
Sorry, it appears my terminal window cut-off the rest. Unfortunately, the log seems to be rotated already.

**Comment by willpower232** [comment]
It could be `“The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior” (ER_CLIENT_INTERACTION_TIMEOUT)` did you configure these?

**Comment by plamenh** [comment]
No, I did not configure anything. Everything was set-up out of the box.
