### ISSUE TITLE
Unable to access SMTP logs

### ISSUE THREAD

**Issue by uhlhosting** [postalserver/postal#2393]
## To Reproduce

1. Try 'postal logs smtp'
2. See error

## Expected behaviour

It is hard to say when it first started, id say after migrating to 2.x for sure, was working fine before.

## Environment details 

 - OS: Ubuntu
 - Browser safari
 - Version [16]
 - Type [desktop]

## Additional information/context

```bash
postal-smtp-1  | log writing failed. "\xE4" from ASCII-8BIT to UTF-8
```

full logs output here, I left it untouched, since it clearly show only SMTP docker has issues reporting me the logs properly, this affects a lot our troubleshooting process when it comes to smtp server.

https://bin.uhl.cloud/?2c2323b835b941e9#HBG8aVi68pHczWPzzu3ftS5mPxxnTTtu4ixCxmHaLtpS

**Comment by slobodangacesa** [comment]
You can find SMTP logs in /opt/postal/log/smtp

**Comment by uhlhosting** [comment]
@slobodangacesa 
that is the path in docker container? I do not have that path in server.

**Comment by slobodangacesa** [comment]
@uhlhosting inside of container, path should be /opt/postal/app/log/, but by default you would have that mapped to host folder:
`  smtp:
    volumes:
      - /opt/postal/log/smtp:/opt/postal/app/log/
`
in /opt/postal/install/docker-compose.override.yml

**Comment by willpower232** [comment]
I don't believe log files are written any more, all the output should go to stdout i.e. docker.

I'm afraid I still don't know what is wrong with your logs though.

**Comment by slobodangacesa** [comment]
that actually depends on this setting, I guess: https://github.com/postalserver/postal/blob/main/config/postal.defaults.yml#L35-L36

**Comment by slobodangacesa** [comment]
I never ran Postal before, so my first (and so far) version is 2.1.2 :) 
in my /opt/postal/install/docker-compose.override.yml I have this:
```
  worker:
    volumes:
      - /opt/postal/log/worker:/opt/postal/app/log/

```
and in postal.yml I have this:
```
logging:
  # Specify options for the logging
  stdout: false

```
and at the end, I do have logs in host's directory: /opt/postal/log/worker

**Comment by uhlhosting** [comment]
I do not have such file at all  /opt/postal/install/docker-compose.override.yml.

**Comment by uhlhosting** [comment]
I managed to get my first readable logs in months almost 1 year now, 

```bash
postal-smtp-1  | log writing failed. "\xE8" from ASCII-8BIT to UTF-8
postal-smtp-1  | log writing failed. "\xFA" from ASCII-8BIT to UTF-8
postal-smtp-1  | log writing failed. "\xB0" from ASCII-8BIT to UTF-8
postal-smtp-1  | W, [2023-04-13T05:06:34.480285 #9]  WARN -- #<Bunny::Session:0x557c36bd5fd0 postal@127.0.0.1:5672, vhost=postal, addresses=[127.0.0.1:5672]>: Recovering from connection.close (CONNECTION_FORCED - broker forced connection closure with reason 'shutdown')
postal-smtp-1  | W, [2023-04-13T05:06:34.480544 #9]  WARN -- #<Bunny::Session:0x557c36bd5fd0 postal@127.0.0.1:5672, vhost=postal, addresses=[127.0.0.1:5672]>: Will recover from a network failure (no retry limit)...
```

Alto is stuck there, and nothing new since.

**Comment by netstx** [comment]
I created a /opt/postal/install/docker-compose.override.yml file with the following conent:

```
version: "3.9"
services:
  smtp:
    volumes:
      - /opt/postal/log/smtp:/opt/postal/app/log/
```

and when running the command "postal logs", I see there's an error:
```

# postal logs
postal-web-1  | Puma starting in single mode...
postal-web-1  | * Puma version: 6.1.1 (ruby 3.2.1-p31) ("The Way Up")
postal-web-1  | *  Min threads: 5
postal-web-1  | *  Max threads: 5
postal-web-1  | *  Environment: production
postal-web-1  | *          PID: 9
postal-web-1  | * Listening on http://127.0.0.1:5000
postal-web-1  | Use Ctrl-C to stop
postal-smtp-1  | rake aborted!
postal-smtp-1  | Errno::EACCES: Permission denied @ rb_sysopen - /opt/postal/app/log/rails.log
postal-smtp-1  | /opt/postal/app/lib/postal/app_logger.rb:9:in `initialize'
postal-smtp-1  | /opt/postal/app/lib/postal/config.rb:100:in `new'
postal-smtp-1  | /opt/postal/app/lib/postal/config.rb:100:in `logger_for'
postal-smtp-1  | /opt/postal/app/config/application.rb:39:in `<class:Application>'
postal-smtp-1  | /opt/postal/app/config/application.rb:16:in `<module:Postal>'
postal-smtp-1  | /opt/postal/app/config/application.rb:15:in `<top (required)>'
postal-smtp-1  | /opt/postal/app/Rakefile:4:in `require_relative'
postal-smtp-1  | /opt/postal/app/Rakefile:4:in `<top (required)>'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `load'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:23:in `run'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:492:in `exec'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:34:in `dispatch'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:28:in `start'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:45:in `block in <top (required)>'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
postal-smtp-1  | /opt/postal/app/bin/bundle:3:in `load'
postal-smtp-1  | /opt/postal/app/bin/bundle:3:in `<main>'
postal-smtp-1  |
postal-smtp-1  |
postal-smtp-1  | Caused by:
postal-smtp-1  | Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/postal/app/log/rails.log
postal-smtp-1  | /opt/postal/app/lib/postal/app_logger.rb:9:in `initialize'
postal-smtp-1  | /opt/postal/app/lib/postal/config.rb:100:in `new'
postal-smtp-1  | /opt/postal/app/lib/postal/config.rb:100:in `logger_for'
postal-smtp-1  | /opt/postal/app/config/application.rb:39:in `<class:Application>'
postal-smtp-1  | /opt/postal/app/config/application.rb:16:in `<module:Postal>'
postal-smtp-1  | /opt/postal/app/config/application.rb:15:in `<top (required)>'
postal-smtp-1  | /opt/postal/app/Rakefile:4:in `require_relative'
postal-smtp-1  | /opt/postal/app/Rakefile:4:in `<top (required)>'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `load'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:23:in `run'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:492:in `exec'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:34:in `dispatch'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:28:in `start'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:45:in `block in <top (required)>'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
postal-smtp-1  | /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
postal-smtp-1  | /opt/postal/app/bin/bundle:3:in `load'
postal-smtp-1  | /opt/postal/app/bin/bundle:3:in `<main>'
postal-smtp-1  | (See full trace by running task with --trace)
```

Any thoughts?

**Comment by arthurzenika** [comment]
Same here, see the logs when launching as debug with docker-compose : 

![image](https://github.com/postalserver/postal/assets/445200/8f4d84c7-a75c-4629-959e-b91457b6992d)

**Comment by uhlhosting** [comment]
@adamcooke any ideas what could cause this? My instance is in this state since migrating to V2*

**Comment by adamcooke** [comment]
Logging is improved in v3 and will hopefully solve these issues 😄
