### ISSUE TITLE
Create organization while specifying a short name doesn't work

### ISSUE THREAD

**Issue by EdenKahane** [postalserver/postal#2561]
## Describe the bug
It seems that when you create a new organization in the web interface, if you specify a short name and a name it doesn't work.
**When I don't specify a short name, everything works fine**
I can find this in my logs : 

```
postal-web-1  | app/controllers/application_controller.rb:93:in `block (2 levels) in render_form_errors'
postal-web-1  | app/controllers/application_controller.rb:91:in `render_form_errors'
postal-web-1  | app/controllers/organizations_controller.rb:30:in `create'
postal-web-1  | lib/postal/tracking_middleware.rb:12:in `call'
postal-web-1  | 172.71.123.183 - - [27/Jul/2023:17:07:34 +0000] "GET /500 HTTP/1.1" 500 46 0.0254
postal-web-1  | [9] [2023-07-27T17:08:25.736] INFO -- : Started GET "/organizations/new" for 141.101.69.33 at 2023-07-27 17:08:25 +0000
postal-web-1  | [9] [2023-07-27T17:08:25.748] INFO -- : Processing by OrganizationsController#new as HTML
postal-web-1  | [9] [2023-07-27T17:08:25.817] INFO -- :   Rendered organizations/new.html.haml within layouts/application (Duration: 8.2ms | Allocations: 844)
postal-web-1  | [9] [2023-07-27T17:08:25.830] INFO -- :   Rendered layout layouts/application.html.haml (Duration: 21.6ms | Allocations: 1451)
postal-web-1  | [9] [2023-07-27T17:08:25.831] INFO -- : Completed 200 OK in 83ms (Views: 24.2ms | ActiveRecord: 18.2ms | Allocations: 2669)
postal-web-1  | 141.101.69.33 - - [27/Jul/2023:17:08:25 +0000] "GET /organizations/new HTTP/1.1" 200 - 0.1133
postal-web-1  | [9] [2023-07-27T17:08:28.087] INFO -- : Started POST "/organizations" for 141.101.68.233 at 2023-07-27 17:08:28 +0000
postal-web-1  | [9] [2023-07-27T17:08:28.088] INFO -- : Processing by OrganizationsController#create as JSON
postal-web-1  | [9] [2023-07-27T17:08:28.088] INFO -- :   Parameters: {"organization"=>{"name"=>"JDR-Poly", "permalink"=>"JDRPoly"}, "commit"=>"Create organization"}
postal-web-1  | [9] [2023-07-27T17:08:28.122] INFO -- : Completed 500 Internal Server Error in 33ms (ActiveRecord: 13.2ms | Allocations: 2327)
postal-web-1  | [9] [2023-07-27T17:08:28.123] FATAL -- :   
postal-web-1  | ArgumentError (wrong number of arguments (given 2, expected 0..1)):
```
Postal doesn't seems to expect two parameters

## To Reproduce

1. Go on the webserver to : postal.exemple.com/organizations/new
2. Enter a name AND a short name.
3. Click on "create organization" 
4. See that nothing happen

## Environment details 
 - Postal version : 2.1.4

**Comment by McPizza0** [comment]
Make sure that shortname dosnt exist elsewhere in the system
I've had this too recently, adding random chars to end of shortname resolves it

**Comment by willpower232** [comment]
Duplicate short names are already dealt with in validation so shouldn't be possible to duplicate

https://github.com/postalserver/postal/blob/7252ed48c88a6bbf472c54242cccbce9614dd7a4/app/models/organization.rb#L34

![image](https://github.com/postalserver/postal/assets/1619102/f5e6f937-82fb-4140-bac4-d787a7df2968)

**Comment by adamcooke** [comment]
This should be resolved and was an issue displaying errors.
