### ISSUE TITLE
messages stuck in queue

### ISSUE THREAD

**Issue by masihfathi** [postalserver/postal#2716]
postal messages stop in the queue in the pending status, while postal status shows every thing work correctly. the issue solve when restarting postal but happened again and again.
i see the postal logs see this issue:
```worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] Internal error: Mysql2::Error: Data too long for column 'output' at row 1
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/database.rb:223:in `block in insert'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/database.rb:222:in `insert'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/delivery.rb:8:in `create'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/message_db/message.rb:124:in `create_delivery'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/app/jobs/unqueue_message_job.rb:413:in `block in perform'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in `each'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in `perform'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/worker.rb:64:in `receive_job'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /opt/postal/app/lib/postal/worker.rb:96:in `block in join_queue'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer.rb:56:in `call'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:1842:in `block in handle_frameset'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `loop'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `catch'
worker_5       | [9] [2023-12-02T01:05:19.353] INFO -- : [BHENIXLFMA] [76::6291 8368583] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `run_loop'
worker_5       | [9] [2023-12-02T01:05:19.357] INFO -- : [BHENIXLFMA] [76::6291 8368583] Queued message was unlocked
worker_5       | [9] [2023-12-02T01:05:19.359] INFO -- : [EVVB5KJG] Finishing up
worker_5       | [9] [2023-12-02T01:05:19.406] INFO -- : [BHENIXLFMA] Finished processing UnqueueMessageJob job in 2227.245330177s
worker_5       | E, [2023-12-02T01:05:19.406291 #9] ERROR -- #<Bunny::Session:0xca58 postal@127.0.0.1:5672, vhost=postal, addresses=[127.0.0.1:5672]>: Uncaught exception from consumer #<Bunny::Consumer:61680 @channel_id=1 @queue=deliver-jobs-outgoing-146 @consumer_tag=bunny-1701461517000-256706572341>: #<Bunny::ChannelAlreadyClosed: cannot use a closed channel! Channel id: 1, closed due to a server-reported channel error: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more> @ /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:2075:in `raise_if_no_longer_open!'```

**Comment by masihfathi** [comment]
hi agian.
the problem is continues and we have this error again.
```ERROR -- #<Bunny::Session:0xca58 postal@127.0.0.1:5672, vhost=postal, addresses=[127.0.0.1:5672]>: Uncaught exception from consumer #<Bunny::Consumer:1229000 @channel_id=1 @queue=deliver-jobs-outgoing-149 @consumer_tag=bunny-1702579847000-96517523738>: #<Bunny::ChannelAlreadyClosed: cannot use a closed channel! Channel id: 1, closed due to a server-reported channel error: PRECONDITION_FAILED - delivery acknowledgement on channel 1 timed out. Timeout value used: 1800000 ms. This timeout value can be configured, see consumers doc guide to learn more> @ /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:2075:in `raise_if_no_longer_open!'```
and message still keep in pending.

**Comment by masihfathi** [comment]
i found this line:
https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_requeuer.rb#L11
 i suspect that requeuer stop and dont get message from mysql and when we restart postal also this task run again and get messages to rabbitmq

**Comment by ugurtam** [comment]
And any solutions ?

**Comment by masihfathi** [comment]
No nothing absolute.
but i think maybe increase consumer_timeout in rabbitmq and also wrapping this line in begin and rescue.
https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_requeuer.rb#L11
```      
       begin
          QueuedMessage.requeue_all
        rescue StandardError => e
          log "Error during requeueing: #{e.message}"
        end
```

**Comment by akhil** [comment]
I do the following to "unstuck" the messages for the queue.
1. Restart the postal processes - postal stop && postal stop periodically to deal with rabbitmq channel problem
2. run the query `update queued_messages set locked_at=NULL, locked_by=NULL;` to unstuck the messages from the queue

Nothing else seems to work so far.

**Comment by ugurtam** [comment]
new versions have been released very recently, I wonder if there is a solution to this problem in those versions

**Comment by TomasMerta** [comment]
There is problem with consumer_timeout. Default 1/2h is to small for big queue. 
`docker exec -it postal-rabbitmq /bin/bash`
`rabbitmqctl eval 'application:set_env(rabbit, consumer_timeout, 25920000000).'`
and restart postal work for me

**Comment by ugurtam** [comment]
> There is problem with consumer_timeout. Default 1/2h is to small for big queue. `docker exec -it postal-rabbitmq /bin/bash` `rabbitmqctl eval 'application:set_env(rabbit, consumer_timeout, 25920000000).'` and restart postal work for me

thanks, I will try this

**Comment by masihfathi** [comment]
> No nothing absolute. but i think maybe increase consumer_timeout in rabbitmq and also wrapping this line in begin and rescue.
> 
> https://github.com/postalserver/postal/blob/2f62baa238fc1102706ee4acf079b7a876b05283/lib/postal/message_requeuer.rb#L11
> 
> ```
>        begin
>           QueuedMessage.requeue_all
>         rescue StandardError => e
>           log "Error during requeueing: #{e.message}"
>         end
> ```

rabbitmq timeout is the problem

**Comment by adamcooke** [comment]
This will hopefully be solved when we remove Rabbit and change message queueing in v3.
