### ISSUE TITLE
'MySQL client is not connected' error

### ISSUE THREAD

**Issue by pdifeo** [postalserver/postal#2780]
## Describe the bug

Yesterday after doing the update everything worked.
This morning instead I receive 

We're sorry, but something went wrong.

`postal logs `

does not give any kind of error.  Happens on two installations on two different servers

## Screenshots
![image](https://github.com/postalserver/postal/assets/8618744/5eb5bc0a-6d7d-44d6-913e-da870ff43e2a)

**Comment by pdifeo** [comment]
I did the rollback to ver 2.1.6 and now it works again. So there must be something still wrong with 2.2.1

**Comment by pdifeo** [comment]
I found this on web instance


```
[9] [2024-02-05T07:01:49.680] INFO -- : Started GET "/org/iudesk" for 213.136.183.90 at 2024-02-05 07:01:49 +0000
[9] [2024-02-05T07:01:49.680] INFO -- : Processing by ServersController#index as HTML
[9] [2024-02-05T07:01:49.680] INFO -- :   Parameters: {"org_permalink"=>"iudesk"}
[9] [2024-02-05T07:01:49.719] INFO -- :   Rendered servers/index.html.haml within layouts/application (Duration: 0.6ms | Allocations: 703)
[9] [2024-02-05T07:01:49.719] INFO -- :   Rendered layout layouts/application.html.haml (Duration: 0.6ms | Allocations: 742)
[9] [2024-02-05T07:01:49.719] INFO -- : Completed 500 Internal Server Error in 39ms (ActiveRecord: 35.1ms | Allocations: 2477)
[9] [2024-02-05T07:01:49.719] FATAL -- :
ActionView::Template::Error (MySQL client is not connected):
    26:             = link_to [organization, server], :class => 'largeList__link' do
    27:               %span.largeList__rightLabel.label{:class => "label--serverStatus-#{server.status.underscore}"}= t("server_statuses.#{server.status.underscore}")
    28:               %p= server.name
    29:               %p.largeList__subText #{number_with_precision server.message_rate, :precision => 2} messages/minute
    30:       .js-searchable__empty.is-hidden
    31:         .noData.noData--clean
    32:           %p.noData__title No servers were found...

```
and after restart postal work again. The question is: if I was able to log in, it means that the connection to MySQL was there. Why does it then give me an error?

**Comment by adamcooke** [comment]
This doesn't sound like an issue with Postal itself. Sounds like a connection issue between Postal and your database server. I can't reproduce this unfortunately.

**Comment by pdifeo** [comment]
I agree with you. But ... on two different servers the same problem? And I repeat the question, if the system manages to log in by querying the database, how come it can do it afterwards

**Comment by adamcooke** [comment]
You can repeat the question but doing so without providing any additional information isn't going to help me answer it.

**Comment by pdifeo** [comment]
Sure. I left version 2.2.1 on one server and rolled back to 2.1.6 on the other. Let's see in the next few days what happens. So I can maybe give you more information

**Comment by willpower232** [comment]
if you are running your MySQL server in docker, make sure you specified it with restart always or unless stopped.

If you aren't then it sounds more like you're running out of memory and MySQL is crashing out or something else is causing your MySQL to stop.

**Comment by pdifeo** [comment]
Surely I have not made myself clear. 

MySQL was always running. The only thing I restarted was postal with the command 
`postal restart`
and it worked again.
As mentioned in previous posts, but I could be wrong, if I managed to log in several times from different browsers, different computers and different networks ... to me it means that MySQL is and continues to be running. In fact docker ps shows

90388f044673 mariadb "docker-entrypoint.s..." 7 weeks ago Up 7 weeks

I have more of a feeling that postal somehow loses the connection pool and only re-establishes it when you restart it.

Lastly, the VM has 8GB of RAM of which there is a good 5GB at the moment

**Comment by siebsie23** [comment]
Hello!
I'm having the exact same issue since 2.2.1. When starting postal it works but after some time I'm getting the following error in the logs:

```
[1835] [2024-02-05T10:11:05.118] FATAL -- :   
ActionView::Template::Error (MySQL client is not connected):
    26:             = link_to [organization, server], :class => 'largeList__link' do
    27:               %span.largeList__rightLabel.label{:class => "label--serverStatus-#{server.status.underscore}"}= t("server_statuses.#{server.status.underscore}")
    28:               %p= server.name
    29:               %p.largeList__subText #{number_with_precision server.message_rate, :precision => 2} messages/minute
    30:       .js-searchable__empty.is-hidden
    31:         .noData.noData--clean
    32:           %p.noData__title No servers were found...
  
lib/postal/message_db/database.rb:304:in `escape'
lib/postal/message_db/database.rb:304:in `block in escape'
lib/postal/message_db/mysql.rb:26:in `client'
lib/postal/message_db/database.rb:342:in `with_mysql'
lib/postal/message_db/database.rb:294:in `escape'
lib/postal/message_db/live_stats.rb:33:in `block in total'
lib/postal/message_db/live_stats.rb:33:in `map'
lib/postal/message_db/live_stats.rb:33:in `total'
app/models/server.rb:133:in `message_rate'
app/views/servers/index.html.haml:29
app/views/servers/index.html.haml:26
app/views/servers/index.html.haml:24:in `each'
app/views/servers/index.html.haml:24
lib/postal/tracking_middleware.rb:12:in `call'
```

My MySQL server is running an working perfectly fine, also there are no issues when running 2.1.6, this only happened after the 2.2.1 update.

**Comment by adamcooke** [comment]
Does it happen fairly soon after starting? Does a restart fix it for a period of time and then it happens again?

**Comment by pdifeo** [comment]
I can tell you that my system February 04, 2024 20:53 Italian time was working (last email sent). This morning not. 
I updated yesterday morning.

**Comment by siebsie23** [comment]
For me it seems to run for about 1-2 hours before it stops working.
Restarting the postal container fixes it but the issue happens again after the same amount of time.

I run a MariaDB server with the same method as @pdifeo but without setting the ip/ports. I connect to it directly by using the same docker network and port 3306.

**Comment by adamcooke** [comment]
I have managed to reproduce this now and will add a fix shortly to have the database connection reestablished automatically.

However, this is caused by your MySQL server becoming unavailable for some reason which might also be worth investigating

**Comment by pdifeo** [comment]
Steps to reproduce

1. docker stop <mariadb image>
2. Visiting https://postal.xxx.yyy, return "We're sorry, but something went wrong."
3. docker start <mariadb image>
4. Visiting https://postal.xxx.yyy, it is possible to login and list of Organizations is showed
5. Selecting an organization, return "We're sorry, but something went wrong."
6. postal restart ... all work again

So, it is true that there was a down of MariaDB but on its restart Postal works partially. In a distributed environment, it is normal that some services might restart.

@adamcooke thanks for the support

**Comment by RickoT** [comment]
This is not resolved, I am still seeing this issue on the posta-sftp side.  Below are the messages from my docker console:

MySQL Container: 
`2024-02-06 10:02:35 4757 [Warning] Aborted connection 4757 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:16 4740 [Warning] Aborted connection 4740 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:16 4617 [Warning] Aborted connection 4617 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:16 4741 [Warning] Aborted connection 4741 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:16 4618 [Warning] Aborted connection 4618 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:16 4616 [Warning] Aborted connection 4616 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:15:18 4599 [Warning] Aborted connection 4599 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:40:05 73473 [Warning] Aborted connection 73473 to db: 'unconnected' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 15:45:00 73592 [Warning] Aborted connection 73592 to db: 'unconnected' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)
2024-02-06 16:39:47 73591 [Warning] Aborted connection 73591 to db: 'postal' user: 'postal-user' host: '10.0.0.176' (Got an error reading communication packets)`


Postal SFTP Container
`
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] An error occurred while processing data from a client.
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] ActiveRecord::StatementInvalid: Mysql2::Error::ConnectionError: Lost connection to MySQL server during query
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
[9] [2024-02-06T16:42:05.880] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activesupport-6.1.7.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/mysql/database_statements.rb:52:in `execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:215:in `execute_and_free'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/mysql/database_statements.rb:57:in `exec_query'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/querying.rb:47:in `find_by_sql'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:843:in `block in exec_queries'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:828:in `exec_queries'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:631:in `load'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:249:in `records'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation.rb:244:in `to_ary'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation/finder_methods.rb:553:in `find_nth_with_limit'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation/finder_methods.rb:538:in `find_nth'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/activerecord-6.1.7.6/lib/active_record/relation/finder_methods.rb:122:in `first'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/client.rb:218:in `authenticate'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/client.rb:199:in `block in auth_login'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/client.rb:49:in `handle'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:184:in `block (2 levels) in run_event_loop'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/postal/smtp_server/server.rb:287:in `run'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/lib/tasks/postal.rake:15:in `block (2 levels) in <top (required)>'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /opt/postal/app/bin/rake:4:in `<top (required)>'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `load'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:23:in `run'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:492:in `exec'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:34:in `dispatch'
[9] [2024-02-06T16:42:05.881] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:28:in `start'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:45:in `block in <top (required)>'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /opt/postal/app/bin/bundle:108:in `load'
[9] [2024-02-06T16:42:05.882] ERROR -- : [NCQ4MC] /opt/postal/app/bin/bundle:108:in `<main>'
`

**Comment by adamcooke** [comment]
That doesn't look related to this issue. This issue is about making connections to database connections that are no longer connected. Your error is 'Lost connection to MySQL server during query' which suggests it was connected and lost the connection during the query.
