### ISSUE TITLE
NoMethodError: undefined method `privacy_mode'

### ISSUE THREAD

**Issue by RickoT** [postalserver/postal#2806]
## Describe the bug

When sending mail, or navigating to the advanced tab of a server config, error received is NoMethodError: undefined method `privacy_mode' in logs.  Mail does not send, or I get an error 500 in the web interface

## To Reproduce
Send an email
or

1. Log in
2. Click on an org
3. Click on a server
4. Click Settings
5. Click Advanced Settings

## Expected behaviour

Mail should send or Advanced Settings should be visible or available

## Environment details 

Postal 2.3.0 running in docker container

## Additional information/context

Log When Sending
```
[9] [2024-02-15T05:52:55.245] ERROR -- : [TTBESO] An error occurred while processing data from a client.
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] NoMethodError: undefined method `privacy_mode' for #<Server id: 21, organization_id: 7, uuid: "02e01d5b-94c2-419f-a493-6055f7f7a5bf", name: "main", mode: "Live", ip_pool_id: nil, created_at: "2023-04-15 03:38:40.247491000 +0000", updated_at: "2023-04-15 03:38:40.247491000 +0000", permalink: "dbk-main", send_limit: nil, deleted_at: nil, message_retention_days: 60, raw_message_retention_days: 30, raw_message_retention_size: 2048, allow_sender: false, token: "dnbdbu", send_limit_approaching_at: nil, send_limit_approaching_notified_at: nil, send_limit_exceeded_at: nil, send_limit_exceeded_notified_at: nil, spam_threshold: 0.5e1, spam_failure_threshold: 0.2e2, postmaster_address: nil, suspended_at: nil, outbound_spam_threshold: nil, domains_not_to_click_track: nil, suspension_reason: nil, log_smtp_data: false>
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/activemodel-6.1.7.6/lib/active_model/attribute_methods.rb:469:in `method_missing'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/received_header.rb:21:in `generate'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/client.rb:369:in `data'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/client.rb:87:in `handle_command'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/client.rb:60:in `handle'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:176:in `block (2 levels) in run_event_loop'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:80:in `select'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:80:in `block in run_event_loop'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:78:in `loop'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:78:in `run_event_loop'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/postal/smtp_server/server.rb:18:in `run'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /opt/postal/app/lib/tasks/postal.rake:17:in `block (2 levels) in <top (required)>'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/bin/rake:25:in `load'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/bin/rake:25:in `<top (required)>'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `load'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli/exec.rb:23:in `run'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:492:in `exec'
[9] [2024-02-15T05:52:55.246] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:34:in `dispatch'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/cli.rb:28:in `start'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:45:in `block in <top (required)>'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /usr/local/bundle/gems/bundler-2.4.9/exe/bundle:33:in `<top (required)>'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /opt/postal/app/bin/bundle:108:in `load'
[9] [2024-02-15T05:52:55.247] ERROR -- : [TTBESO] /opt/postal/app/bin/bundle:108:in `<main>'
```
Log when navigating to Advanced Settings
```
[9] [2024-02-15T06:06:05.168] INFO -- :   Rendered layout layouts/application.html.haml (Duration: 29.5ms | Allocations: 29683)
[9] [2024-02-15T06:06:05.168] INFO -- : Completed 500 Internal Server Error in 48ms (ActiveRecord: 14.3ms | Allocations: 31547)
[9] [2024-02-15T06:06:05.169] FATAL -- :   
ActionView::Template::Error (undefined method `privacy_mode' for #<Server id: 21, organization_id: 7, uuid: "02e01d5b-94c2-419f-a493-6055f7f7a5bf", name: "main", mode: "Live", ip_pool_id: nil, created_at: "2023-04-14 20:38:40.247491000 -0700", updated_at: "2023-04-14 20:38:40.247491000 -0700", permalink: "dbk-main", send_limit: nil, deleted_at: nil, message_retention_days: 60, raw_message_retention_days: 30, raw_message_retention_size: 2048, allow_sender: false, token: "dnbdbu", send_limit_approaching_at: nil, send_limit_approaching_notified_at: nil, send_limit_exceeded_at: nil, send_limit_exceeded_notified_at: nil, spam_threshold: 0.5e1, spam_failure_threshold: 0.2e2, postmaster_address: nil, suspended_at: nil, outbound_spam_threshold: nil, domains_not_to_click_track: nil, suspension_reason: nil, log_smtp_data: false>):
    22:         .fieldSet__field
    23:           = f.label :privacy_mode, "Privacy mode", :class => 'fieldSet__label'
    24:           .fieldSet__input
    25:             = f.select :privacy_mode, [["Disabled", false], ["Enabled", true]], {}, :class => 'input input--select'
    26:             %p.fieldSet__text If enabled, when Postal adds Received headers to e-mails it will not include IP or hostname information of the client submitting the message.
    27:         .fieldSet__field
    28:           = f.label :log_smtp_data, "Log SMTP data?", :class => 'fieldSet__label'
  
app/views/servers/advanced.html.haml:25
app/views/servers/advanced.html.haml:9
lib/postal/tracking_middleware.rb:14:in `call'
10.255.0.2 - - [15/Feb/2024:06:06:05 +0000] "GET /500 HTTP/1.1" 500 1477 0.0528
```

**Comment by catphish** [comment]
This suggests that the code has been upgraded but database migrations have not been executed.

**Comment by RickoT** [comment]
I am running this in docker.  Can I run this command in ANY of the docker containers?

**Comment by RickoT** [comment]
Took the risk and ran it, seems to have worked, thanks!

**Comment by catphish** [comment]
> I am running this in docker. Can I run this command in ANY of the docker containers?

Yes. This will hopefully be better documented at some point.
