### ISSUE TITLE
Getting Internal error: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by Jank1310** [postalserver/postal#2821]
One email of several with nearly identical content cannot be send due to the following error:

`Internal error: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT`

The email is submitted to postal using the rest api.
What exactly does this error mean and how can it be fixed?

Postal Version: 2.3.1

Edit Stacktrace:

```
[9] [2024-02-27T09:18:06.060] INFO -- : [YAVWZM9J1L] [1::2675 2684] Got queued message with exclusive lock
[9] [2024-02-27T09:18:06.081] INFO -- : [YAVWZM9J1L] [1::2675 2684] Internal error: Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
[9] [2024-02-27T09:18:06.082] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:845:in `[]='
[9] [2024-02-27T09:18:06.083] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:845:in `sender'
[9] [2024-02-27T09:18:06.084] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:527:in `block in fetch_resource'
[9] [2024-02-27T09:18:06.084] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1125:in `block (3 levels) in resolv'
[9] [2024-02-27T09:18:06.085] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1123:in `each'
[9] [2024-02-27T09:18:06.085] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1123:in `block (2 levels) in resolv'
[9] [2024-02-27T09:18:06.086] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1122:in `each'
[9] [2024-02-27T09:18:06.087] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1122:in `block in resolv'
[9] [2024-02-27T09:18:06.087] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1120:in `each'
[9] [2024-02-27T09:18:06.088] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:1120:in `resolv'
[9] [2024-02-27T09:18:06.088] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:521:in `fetch_resource'
[9] [2024-02-27T09:18:06.089] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:507:in `each_resource'
[9] [2024-02-27T09:18:06.090] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:498:in `getresources'
[9] [2024-02-27T09:18:06.095] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/mx_lookup.rb:29:in `block in resolve'
[9] [2024-02-27T09:18:06.096] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/lib/ruby/3.2.0/resolv.rb:298:in `open'
[9] [2024-02-27T09:18:06.097] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/mx_lookup.rb:27:in `resolve'
[9] [2024-02-27T09:18:06.098] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/mx_lookup.rb:9:in `lookup'
[9] [2024-02-27T09:18:06.099] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/smtp_sender.rb:228:in `servers'
[9] [2024-02-27T09:18:06.099] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/smtp_sender.rb:20:in `start'
[9] [2024-02-27T09:18:06.100] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/app/jobs/unqueue_message_job.rb:462:in `cached_sender'
[9] [2024-02-27T09:18:06.100] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/app/jobs/unqueue_message_job.rb:386:in `block in perform'
[9] [2024-02-27T09:18:06.100] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/app/jobs/unqueue_message_job.rb:34:in `each'
[9] [2024-02-27T09:18:06.101] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/app/jobs/unqueue_message_job.rb:34:in `perform'
[9] [2024-02-27T09:18:06.101] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/worker.rb:66:in `receive_job'
[9] [2024-02-27T09:18:06.103] INFO -- : [YAVWZM9J1L] [1::2675 2684] /opt/postal/app/lib/postal/worker.rb:98:in `block in join_queue'
[9] [2024-02-27T09:18:06.104] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer.rb:56:in `call'
[9] [2024-02-27T09:18:06.104] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:1842:in `block in handle_frameset'
[9] [2024-02-27T09:18:06.104] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
[9] [2024-02-27T09:18:06.105] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `loop'
[9] [2024-02-27T09:18:06.105] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
[9] [2024-02-27T09:18:06.105] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `catch'
[9] [2024-02-27T09:18:06.106] INFO -- : [YAVWZM9J1L] [1::2675 2684] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `run_loop'
[9] [2024-02-27T09:18:06.111] INFO -- : [YAVWZM9J1L] [1::2675 2684] Queued message was unlocked
```

**Comment by adamcooke** [comment]
Can you confirm the domain for the recipient of the message you're sending to?

**Comment by Jank1310** [comment]
Ah, thanks for pointing that out. There was indeed a non-ascii "‐" in the domain 🤯

**Comment by adamcooke** [comment]
I'm going to reopen this because, even if you did have a non-ascii character, it should not have errored like this.

**Comment by adamcooke** [comment]
This is now fixed in v3.

**Comment by Trapulo** [comment]
Hi, I have same problem with version 3.3.4 sending to a @gmail.com recipient....
