### ISSUE TITLE
Upgrade to v3 failed due to migration error 

### ISSUE THREAD

**Issue by arnebr** [postalserver/postal#2842]
## Describe the bug

Upgrade to v3 failed due to migration error:
```
Database schema is already loaded. Running migrations with db:migrate

== 20240214132253 AddLockFieldsToWebhookRequests: migrating ===================
-- add_column(:webhook_requests, :locked_by, :string)
rake aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

Mysql2::Error: Duplicate column name 'locked_by'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:638:in `block (2 levels) in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:637:in `block in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:636:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:628:in `add_column'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:965:in `block in method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:954:in `method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration/compatibility.rb:56:in `add_column'
/opt/postal/app/db/migrate/20240214132253_add_lock_fields_to_webhook_requests.rb:6:in `change'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:905:in `exec_migration'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:887:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1462:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `each'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1166:in `up'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <top (required)>'
/opt/postal/app/lib/tasks/postal.rake:35:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/opt/postal/app/bin/bundle:108:in `load'
/opt/postal/app/bin/bundle:108:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Duplicate column name 'locked_by' (ActiveRecord::StatementInvalid)
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:638:in `block (2 levels) in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:637:in `block in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:636:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:628:in `add_column'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:965:in `block in method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:954:in `method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration/compatibility.rb:56:in `add_column'
/opt/postal/app/db/migrate/20240214132253_add_lock_fields_to_webhook_requests.rb:6:in `change'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:905:in `exec_migration'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:887:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1462:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `each'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1166:in `up'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <top (required)>'
/opt/postal/app/lib/tasks/postal.rake:35:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/opt/postal/app/bin/bundle:108:in `load'
/opt/postal/app/bin/bundle:108:in `<main>'

Caused by:
Mysql2::Error: Duplicate column name 'locked_by' (Mysql2::Error)
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:638:in `block (2 levels) in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:637:in `block in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:636:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:628:in `add_column'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:965:in `block in method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:935:in `say_with_time'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:954:in `method_missing'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration/compatibility.rb:56:in `add_column'
/opt/postal/app/db/migrate/20240214132253_add_lock_fields_to_webhook_requests.rb:6:in `change'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:905:in `exec_migration'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:888:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:887:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1095:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1462:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `each'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1382:in `migrate_without_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `block in migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1477:in `with_advisory_lock'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1331:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1166:in `up'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1141:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:262:in `migrate'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <top (required)>'
/opt/postal/app/lib/tasks/postal.rake:35:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
/opt/postal/app/bin/bundle:108:in `load'
/opt/postal/app/bin/bundle:108:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```
## To Reproduce

When running postal upgrade after git pull origin the migration fails

**Comment by arnebr** [comment]
It seems the initial error was different: 
`== 20240214132253 AddLockFieldsToWebhookRequests: migrating ===================
-- add_column(:webhook_requests, :locked_by, :string)
   -> 0.0105s
-- add_column(:webhook_requests, :locked_at, :datetime, {:precision=>nil})
   -> 0.0147s
-- add_index(:webhook_requests, :locked_by)
rake aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

Mysql2::Error: Index column size too large. The maximum column size is 767 bytes
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `_query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:151:in `block in query'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.5.6/lib/mysql2/client.rb:150:in `query'
/usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:638:in `block (2 levels) in raw_execute'
/usr/local/bundle/gems/activesupport-7.0.8.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'`

**Comment by adamcooke** [comment]
What version of MySQL/MariaDB are you using?

**Comment by arnebr** [comment]
MariaDB 10.6.16 - that seems to be the issue. Upgrading right now.

**Comment by arnebr** [comment]
ALTER TABLE authie_sessions ROW_FORMAT=DYNAMIC;
Fixed the problem

**Comment by adamcooke** [comment]
Glad you got this sorted.

I have added a note to the upgrade page to note that people do need to be aware of the row format on their tables before upgrading.

https://docs.postalserver.io/getting-started/upgrade-to-v3#database-considerations

**Comment by phillmorgan28** [comment]
The docs state "It is important that any pre-existing tables in your database are set up with the DYNAMIC row format." .. does this include all of the postal-server-X databases as well, or just the main postal db?

**Comment by adamcooke** [comment]
I'd recommend making sure all tables in all databases are set like that to avoid any potential issue in the future.

**Comment by phillmorgan28** [comment]
Ok thanks, that's quite a job. For anyone that want's a nice quick and easy way to do that, adjust this to your needs and run

```
#!/bin/bash

# Get a list of all databases
databases=$(mysql -u your_username -p'your_password' -e 'SHOW DATABASES;' | grep -Ev 'Database|information_schema|performance_schema|mysql')

# Loop through each database
for db in $databases; do
    # Get a list of all tables in the current database
    tables=$(mysql -u your_username -p'your_password' $db -e 'SHOW TABLES;' | grep -v 'Tables_in_')

    # Loop through each table
    for table in $tables; do
        # Execute the ALTER TABLE command, quoting table names with backticks
        mysql -u your_username -p'your_password' $db -e "ALTER TABLE \`$table\` ROW_FORMAT=DYNAMIC;"
    done
done
```
