### ISSUE TITLE
Postal Don't Override Environment Variables

### ISSUE THREAD

**Issue by omertahaoztop** [postalserver/postal#2857]
## Describe the bug

I was upgrading from Postal 2 to Postal 3, and it seems that the parameters which worked in the Postal 2 configuration are not being overridden in Postal 3:

Postal 2 Config: 
```

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: <user>
  password: <password>
  from_name: Postal
  from_address: <e-mail>

smtp_server:
  # Specify configuration to the Postal SMTP server
  port: 2525
  tls_enabled: true
  tls_certificate_path: /opt/postal/app/config/fullchain.pem
  tls_private_key_path: /opt/postal/app/config/privkey.pem
```

Postal 3 Config:

```
smtp:
  host: 127.0.0.1
  port: 2525
  username: <username>
  password: <password>
  authentication_type: login
  enable_starttls: false
  enable_starttls_auto: true
  openssl_verify_mode: peer
  from_name: Postal
  from_address:  <e-mail>


smtp_server:
  default_port: 2525
  default_bind_address: '*'
  default_health_server_port: 9091
  default_health_server_bind_address: 0.0.0.0
  tls_enabled: true
  tls_certificate_path: /opt/postal/app/config/smtp/fullchain.pem
  tls_private_key_path: /opt/postal/app/config/smtp/privkey.pem
  tls_ciphers:
  ssl_version: SSLv23
  proxy_protocol: false
  log_connections: false
  max_message_size: 14
  log_ip_address_exclusion_matcher:

```

## To Reproduce

1) Check SSL/TLS enabled with testssl.sh and i  am getting this:

```
 xx.xx.x.xx:2525 doesn't seem to be a TLS/SSL enabled server
```

2) And postal-smtp logs say:

```
2024-03-07 15:58:11 +0000 ERROR  An error occurred while processing data from a client. trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  Errno::ENOENT: No such file or directory @ rb_sysopen - /config/smtp.cert trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:19:in `read' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:19:in `tls_certificates' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:63:in `ssl_context' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:226:in `block (2 levels) in run_event_loop' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:106:in `select' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:106:in `block in run_event_loop' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:104:in `loop' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:104:in `run_event_loop' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:39:in `block in run' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  /opt/postal/app/app/lib/smtp_server/server.rb:37:in `run' trace_id=C04XDAUI component=smtp-server
2024-03-07 15:58:11 +0000 ERROR  script/smtp_server.rb:13:in `<main>' trace_id=C04XDAUI component=smtp-server
```

3) Run to *postal test-app-smtp* for test is returning with: `Message has been sent successfully.`

Thank you in advance.

**Comment by adamcooke** [comment]
This is resolved in 3.1.1
