### ISSUE TITLE
Password reset results in error

### ISSUE THREAD

**Issue by sandroshu** [postalserver/postal#2906]
## Describe the bug

Submitting the E-mail address on the "Lost password" page result in error.

## To Reproduce

1. Go to 'Lost password'
2. Type user e-mail address
3. Submit

## Expected behaviour

Receive password reset e-mail

## Screenshots

https://imgur.com/XRCykgV

## Environment details 

 - OS: Debian 11
 - Firefox

## Additional information/context

```
2024-04-02 19:09:37 +0000 INFO   event=send_email transaction=9f30780956d509ef73f4 message_id=660c57f13dcde_ae54c2435c@postal.xxx.mail subject=Reset your Postal password from=[nil] to=x@x.hu
2024-04-02 19:09:37 +0000 ERROR  POST /login/reset (500) event=request transaction=9f30780956d509ef73f4 controller=SessionsController action=begin_password_reset format=html method=POST path=/login/reset request_id=a3cd2ff7-552d-4b8b-afca-0048f9c5ccb1 ip_address=x.x.x.x status=500 db_runtime=9.907332420349121 exception_class=Errno::ECONNREFUSED exception_message=Connection refused - connect(2) for "127.0.0.1" port 2525 exception_backtrace=/opt/postal/app/config/initializers/smtp_extensions.rb:32:in `initialize'\n/opt/postal/app/config/initializers/smtp_extensions.rb:32:in `open'\n/opt/postal/app/config/initializers/smtp_extensions.rb:32:in `tcp_socket'\n/usr/local/bundle/gems/net-smtp-0.4.0.1/lib/net/smtp.rb:641:in `block in do_start'
194.38.104.99 - - [02/Apr/2024:19:09:37 +0000] "GET /500 HTTP/1.1" 500 1477 0.0338
```

**Comment by adamcooke** [comment]
You haven't configured an SMTP server for it to use when sending the password reset emails. This is not a bug. See: https://github.com/postalserver/postal/blob/main/doc/config/yaml.yml#L155-L175
