### ISSUE TITLE
when trying to build a mailserver after fresh installation we get an internal server error

### ISSUE THREAD

**Issue by rakurtz** [postalserver/postal#3043]
## Describe the bug

i followed the installation guide from https://docs.postalserver.io/getting-started/installation and was abled to connect to postal web interface and login with my just created user.

i could create my first organization. but right after that i wanted to build a mailserver. i added a name and hit "build". Then nothing happens and i could see that in the javascript console it shows an internal server error.

```
Failed to load resource: the server responded with a status of 500 ()
```

## Screenshots
<img width="753" alt="Screenshot1" src="https://github.com/postalserver/postal/assets/70766440/1be00626-f14f-4543-ae54-c08aca5507c0">

## Environment details 

 - OS: ubuntu 24.04
 - Browser: safari
 - Version: 3.3.4

**Comment by rakurtz** [comment]
this is the error message from `docker logs postal-web-1`

```
2024-07-11 15:16:13 +0000 ERROR  POST /org/xxxx/servers (500) event=request transaction=f375bbd013df0c241620 controller=ServersController action=create format=json method=POST path=/org/xxxx/servers request_id=fd5b836b-320f-4b3e-ae1e-48e88b0bfbf4 ip_address=80.155.xxx.xxx status=500 db_runtime=11.046738999895751 exception_class=NoMethodError exception_message=undefined method `query' for nil:NilClass exception_backtrace=/opt/postal/app/lib/postal/message_db/database.rb:326:in `query_on_connection'\n/opt/postal/app/lib/postal/message_db/database.rb:318:in `block in query'\n/opt/postal/app/lib/postal/message_db/connection_pool.rb:20:in `use'\n/opt/postal/app/lib/postal/message_db/database.rb:345:in `with_mysql'
80.155.176.178 - - [11/Jul/2024:15:16:13 +0000] "GET /500 HTTP/1.1" 500 46 0.0335

```

**Comment by rakurtz** [comment]
When you are too dumb to also set your password for the message_db in config/postal.yaml...

Sorry for bothering. Problem solved.
