### ISSUE TITLE
bigdecimal gem is missing from dependencies

### ISSUE THREAD

**Issue by lukasmrtvy** [postalserver/postal#666]
bash-4.4$ /opt/postal/bin/postal initialize 

```
Initializing database
rake aborted!
LoadError: cannot load such file -- bigdecimal
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/xml_mini.rb:5:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/xml_mini.rb:5:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/duration.rb:3:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/duration.rb:3:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/file_update_checker.rb:3:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/file_update_checker.rb:3:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/i18n_railtie.rb:4:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/i18n_railtie.rb:4:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/railtie.rb:4:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/railtie.rb:4:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails.rb:17:in `require'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails.rb:17:in `<top (required)>'
/opt/postal/config/application.rb:3:in `require'
/opt/postal/config/application.rb:3:in `<top (required)>'
/opt/postal/Rakefile:4:in `require_relative'
/opt/postal/Rakefile:4:in `<top (required)>'
/opt/postal/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

EDIT;
These are missing from https://github.com/atech/postal/blob/master/Gemfile

gem 'bigdecimal'
gem 'etc'
gem 'tzinfo-data'

Found another dependency `ruby-irb` for /usr/bin/postal console

**Comment by willpower232** [comment]
Thanks for the information, can you tell us which OS and version you are using?

**Comment by lukasmrtvy** [comment]
Alpine:3.8 in Docker
I will paste Dockerfile when it will be ready. This was my requirement: https://github.com/atech/postal/issues/657

**Comment by willpower232** [comment]
Interesting, Alpine isn't directly supported but good to know where the gaps are.

You could make a pull request to add in the dependencies, it would probably be worth recording their requirement in the repo that way.
